name: Test X64 Docker image

on:
  push:
    branches:
      - "async"

jobs:
  Provision-Runners:
    name: Provision-Runners
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: AWS Cli Processing
        run: |
          #!/bin/bash
          # Please add comma at the end of the RUNNERS strings
          # Don't add space after commas
          # RUNNERS="odfe-rpm-im-nosec-arm64,odfe-rpm-alerting-nosec-arm64,odfe-rpm-sql-nosec-arm64,odfe-rpm-knn-nosec-arm64,odfe-rpm-ad-nosec-arm64,"
          # RUNNERS+="odfe-rpm-sql-arm64,odfe-rpm-ad-arm64,odfe-rpm-alerting-arm64,"
          # RUNNERS+="odfe-rpm-ad-kibana-nosec-arm64,odfe-rpm-sql-kibana-nosec-arm64,"
          # RUNNERS+="odfe-rpm-ad-kibana-arm64,odfe-rpm-sec-kibana-arm64,odfe-rpm-kibana-nb-nosec-arm64"
          RUNNERS="odfe-rpm-async-arm64"
          release-tools/scripts/setup_runners.sh run $RUNNERS ${{ secrets.ODFE_RELEASE_BOT_PUBLIC_PRIVATE_READ_WRITE_TOKEN }} ami-0ef0c96643bbd01f2

  Test-Async-NoSec:
    needs: [Provision-Runners]
    name: Test-Async-NoSec
    runs-on: [self-hosted, Linux, ARM64, odfe-rpm-async-arm64]
    steps:
      - uses: actions/checkout@v1
      - name: Required Packages
        run: release-tools/scripts/required_packages.sh
      - name: Retrieve plugin tags
        run: echo "p_tag_async=$(release-tools/scripts/plugin_tag.sh opendistro-for-elasticsearch/asynchronous-search)" >> $GITHUB_ENV
      - uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/asynchronous-search
          ref: ${{env.p_tag_async}}
      - name: IT for IM NoSec
        run: |
          release-tools/scripts/setup_runners_service.sh rpm --es-nosec arm64
          export PATH=$JAVA_HOME:$PATH; cd $GITHUB_WORKSPACE/../asynchronous-search; pwd
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest

  CleanUp-Runners:
    needs: [Test-Async-NoSec]
    if: always()
    name: CleanUp-Runners
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: AWS Cli Processing
        run: |
          #!/bin/bash
          # Please add comma at the end of the RUNNERS strings
          # Don't add space after commas
          # RUNNERS="odfe-rpm-im-nosec-arm64,odfe-rpm-alerting-nosec-arm64,odfe-rpm-sql-nosec-arm64,odfe-rpm-knn-nosec-arm64,odfe-rpm-ad-nosec-arm64,"
          # RUNNERS+="odfe-rpm-sql-arm64,odfe-rpm-ad-arm64,odfe-rpm-alerting-arm64,"
          # RUNNERS+="odfe-rpm-ad-kibana-nosec-arm64,odfe-rpm-sql-kibana-nosec-arm64,"
          # RUNNERS+="odfe-rpm-ad-kibana-arm64,odfe-rpm-sec-kibana-arm64,odfe-rpm-kibana-nb-nosec-arm64"
          RUNNERS="odfe-rpm-async-arm64"
          release-tools/scripts/setup_runners.sh terminate $RUNNERS ${{ secrets.ODFE_RELEASE_BOT_PUBLIC_PRIVATE_READ_WRITE_TOKEN }}
