name: Test X64 Docker image

on:
  push:
    branches:
      - "async"

jobs:
  Get-versions:
    name: Get-versions
    runs-on: ubuntu-18.04
    outputs:
      es_version: ${{ env.es_version }}
      od_version: ${{ env.od_version }}
      p_tag_async: ${{ env.p_tag_async }}
    steps:
      - uses: actions/checkout@v1
      - name: Get all versions and tags
        run: |
          release-tools/scripts/required_packages.sh
          echo "es_version=$(release-tools/scripts/version-info.sh --es)" >> $GITHUB_ENV
          echo "od_version=$(release-tools/scripts/version-info.sh --od)" >> $GITHUB_ENV
          echo "p_tag_async=$(release-tools/scripts/plugin_tag.sh opendistro-for-elasticsearch/asynchronous-search)" >> $GITHUB_ENV

  Test-Async-NoSec:
    needs: [Get-versions]
    runs-on: windows-2019
    name: Test-Async-NoSec
    strategy:
      fail-fast: false
      matrix:
        java: [14]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/checkout@v1
        with:
           repository: opendistro-for-elasticsearch/asynchronous-search
           ref: ${{needs.Get-versions.outputs.p_tag_im}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
       
      - name: RUN ES and Async IntegTest
        run: |
          release-tools\scripts\setup_runners_service_windows.ps1 --es-nosec ${{needs.Get-versions.outputs.od_version}}
          $ErrorActionPreference = 'SilentlyContinue'
          echo running tests
          cd ..\asynchronous-search
          dir
          ./gradlew.bat integTest -D tests.rest.cluster=localhost:9200 -D tests.cluster=localhost:9200 -D tests.clustername=es-integrationtest --stacktrace          
